# Example usage of the ArXiv project source

In [2]:
%load_ext autoreload
%autoreload 2

import sys
if '..' not in sys.path:
    sys.path.append('..')

In [3]:
from arxiv_analysis import load
arxiv = load.ArxivDataset.load(
    loc='../data/example/arxiv_meta.jsonl'
)

In [4]:
arxiv.df.head()

,submitter,authors,title,comments,journal-ref,categories,abstract,update_date
0,"(Pavel, Nadolsky)","(C., Bal\'azs, ,, E., L., Berger, ,, P., M., N...","(Calculation, of, prompt, diphoton, production...","(37, pages, ,, 15, figures, ;, published, vers...","(Phys, ., Rev, ., D76:013009,2007)",[5],"(A, fully, differential, calculation, in, pert...",2008-11-26
1,"(Louis, Theran)","(Ileana, Streinu, and, Louis, Theran)","(Sparsity, -, certifying, Graph, Decompositions)","(To, appear, in, Graphs, and, Combinatorics)",None,"[7, 3]","(We, describe, a, new, algorithm, ,, the, $, (...",2008-12-13
2,"(Hongjun, Pan)","(Hongjun, Pan)","(The, evolution, of, the, Earth, -, Moon, syst...","(23, pages, ,, 3, figures)",None,[9],"(The, evolution, of, Earth, -, Moon, system, i...",2008-01-13
3,"(David, Callan)","(David, Callan)","(A, determinant, of, Stirling, cycle, numbers,...","(11, pages)",None,[7],"(We, show, that, a, determinant, of, Stirling,...",2007-05-23
4,"(Alberto, Torchinsky)","(Wael, Abu, -, Shammala, and, Alberto, Torchin...","(From, dyadic, $, \Lambda_{\alpha}$, to, $, \L...",None,"(Illinois, J., Math, ., 52, (, 2008, ), no.2, ...","[6, 8]","(In, this, paper, we, show, how, to, compute, ...",2013-10-15

In [5]:
arxiv[:2]

,submitter,authors,title,comments,journal-ref,categories,abstract,update_date
0704.0001,"(Pavel, Nadolsky)","(C., Bal\'azs, ,, E., L., Berger, ,, P., M., N...","(Calculation, of, prompt, diphoton, production...","(37, pages, ,, 15, figures, ;, published, vers...","(Phys, ., Rev, ., D76:013009,2007)",[hep-ph],"(A, fully, differential, calculation, in, pert...",2008-11-26
0704.0002,"(Louis, Theran)","(Ileana, Streinu, and, Louis, Theran)","(Sparsity, -, certifying, Graph, Decompositions)","(To, appear, in, Graphs, and, Combinatorics)",None,"[math.co, cs.cg]","(We, describe, a, new, algorithm, ,, the, $, (...",2008-12-13